version: '3.5'

services:
  zookeeper1:
    image: zookeeper:3.4
    hostname: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper2:
    image: zookeeper:3.4
    hostname: zookeeper2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper3:
    image: zookeeper:3.4
    hostname: zookeeper3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=0.0.0.0:2888:3888

  namenode1:
    image: bde2020/hadoop-namenode:1.2.1-hadoop2.8-java8
    env_file:
      - ./hadoop/env
    expose:
      - "9000"
    ports:
      - "50070:50070"
    entrypoint: >
      sh -c "/entrypoint.sh &&
             /opt/hadoop-2.8.0/bin/hdfs namenode -format -force &&
             /opt/hadoop-2.8.0/sbin/hadoop-daemon.sh --config /etc/hadoop start namenode &&
             sleep infinity"

  datanode1: &datanode
    image: bde2020/hadoop-datanode:1.2.1-hadoop2.8-java8
    depends_on:
      - namenode1
    env_file:
      - ./hadoop/env
    entrypoint: >
      sh -c "/entrypoint.sh &&
             /opt/hadoop-2.8.0/sbin/hadoop-daemon.sh --config /etc/hadoop start datanode &&
             sleep infinity"

  datanode2: *datanode
  datanode3: *datanode
  datanode4: *datanode

  jobmanager1:
    build: &flinkbuild
      context: flink
      dockerfile: ${FLINK_DOCKERFILE-Dockerfile}
      args: &proxy
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager1

  taskmanager1: &taskmanager
    build: *flinkbuild
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager1
    tmpfs:
      - '/tmp:exec,mode=777'  # probably not necessary due to the adjusted tmp dir
    volumes:
      - '/media/'
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager1
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=8

  taskmanager2: *taskmanager
  taskmanager3: *taskmanager

  job:
    build:
      context: .
      dockerfile: core/Dockerfile
      args: *proxy
    depends_on:
      - jobmanager1
      - taskmanager1
      - taskmanager2
      - taskmanager3
